#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../../scripts/lib/transcript.sh"

PASS=0; FAIL=0
assert_eq() { local d="$1" e="$2" a="$3"; [[ "$e" == "$a" ]] && { echo "  ✓ $d"; ((PASS++)) || true; } || { echo "  ✗ $d: '$e' vs '$a'"; ((FAIL++)) || true; }; }

FIX="$SCRIPT_DIR/../fixtures"
CWD="/tmp/fake-project"

echo "=== transcript.sh tests ==="

echo "-- single-turn feature --"
r=$(transcript_parse_current_turn "$FIX/transcript-v15-feature.jsonl" "[]" "$CWD")
assert_eq "turn_number" "1" "$(echo "$r" | jq -r '.turn_number')"
assert_eq "user_word_count" "7" "$(echo "$r" | jq -r '.user_word_count')"
assert_eq "tool_call_count" "4" "$(echo "$r" | jq -r '.tool_call_count')"
assert_eq "rate-limit in new files" "true" "$(echo "$r" | jq '[.new_files_this_turn[] | select(contains("rate-limit"))] | length > 0')"

echo "-- agentic multi-turn: only LAST user's turn --"
r=$(transcript_parse_current_turn "$FIX/transcript-v15-agentic.jsonl" "[]" "$CWD")
assert_eq "turn_number 2" "2" "$(echo "$r" | jq -r '.turn_number')"
assert_eq "tool_call_count 2" "2" "$(echo "$r" | jq -r '.tool_call_count')"

echo "-- multi-stop: multiple assistant entries in same turn aggregated --"
r=$(transcript_parse_current_turn "$FIX/transcript-v15-multi-stop.jsonl" "[]" "$CWD")
assert_eq "turn_number 1 (single user)" "1" "$(echo "$r" | jq -r '.turn_number')"
assert_eq "tool_call_count 3 (aggregated)" "3" "$(echo "$r" | jq -r '.tool_call_count')"

echo "-- new_files excludes previously seen --"
r=$(transcript_parse_current_turn "$FIX/transcript-v15-agentic.jsonl" '["src/auth/jwt.ts"]' "$CWD")
assert_eq "one new file" "1" "$(echo "$r" | jq -r '.new_files_this_turn | length')"

echo "-- user content as array (tool_result block) returns usable string --"
tmp=$(mktemp).jsonl
cat > "$tmp" <<'JSONL'
{"type":"user","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"x","content":"prev result"},{"type":"text","text":"Now fix the bug I mentioned"}]}}
{"type":"assistant","message":{"role":"assistant","content":[{"type":"tool_use","id":"d1","name":"Edit","input":{"file_path":"fix.ts"}}]}}
JSONL
r=$(transcript_parse_current_turn "$tmp" "[]" "$CWD")
assert_eq "user_msg extracted from array" "Now fix the bug I mentioned" "$(echo "$r" | jq -r '.user_msg')"
rm -f "$tmp"

echo "-- domain_guess from file paths (second level) --"
r=$(transcript_parse_current_turn "$FIX/transcript-v15-agentic.jsonl" "[]" "$CWD")
assert_eq "domain_guess auth" "auth" "$(echo "$r" | jq -r '.domain_guess')"

echo "-- cwd fallback when no files --"
tmp=$(mktemp).jsonl
cat > "$tmp" <<'JSONL'
{"type":"user","message":{"role":"user","content":"hi"}}
{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"hello"}]}}
JSONL
r=$(transcript_parse_current_turn "$tmp" "[]" "/tmp/my-project")
assert_eq "domain_guess from cwd" "my-project" "$(echo "$r" | jq -r '.domain_guess')"
rm -f "$tmp"

echo "-- file_size exposed for idempotency signature --"
r=$(transcript_parse_current_turn "$FIX/transcript-v15-feature.jsonl" "[]" "$CWD")
fs=$(echo "$r" | jq -r '.file_size')
[[ "$fs" -gt 100 ]] && { echo "  ✓ file_size > 100 ($fs)"; ((PASS++)) || true; } || { echo "  ✗ unexpected file_size: $fs"; ((FAIL++)) || true; }

echo "-- missing transcript returns error field --"
r=$(transcript_parse_current_turn "/nonexistent.jsonl" "[]" "$CWD" || true)
assert_eq "error field" "missing_transcript" "$(echo "$r" | jq -r '.error // ""')"

echo "-- synthetic user messages (slash-command wrappers, system-reminder) are skipped --"
# CC injects pseudo-user-messages around slash commands and system events. Without
# filtering, these poison user_msg with literal "<local-command-caveat>..." text and
# the LLM (or, downstream, CC's own auto-naming) treats them as user intent.
tsyn=$(mktemp).jsonl
cat > "$tsyn" <<'JSONL'
{"type":"user","message":{"role":"user","content":"Implement the OAuth callback handler please"}}
{"type":"assistant","message":{"role":"assistant","content":[{"type":"tool_use","id":"d1","name":"Edit","input":{"file_path":"src/auth/oauth.ts"}}]}}
{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"}}
{"type":"user","message":{"role":"user","content":"<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>"}}
{"type":"user","message":{"role":"user","content":"<local-command-stdout>Set model to Opus 4.7</local-command-stdout>"}}
{"type":"user","message":{"role":"user","content":"<system-reminder>SessionStart hook fired</system-reminder>"}}
JSONL
r=$(transcript_parse_current_turn "$tsyn" "[]" "$CWD")
assert_eq "user_msg ignores synthetics, falls back to real prompt" "Implement the OAuth callback handler please" "$(echo "$r" | jq -r '.user_msg')"

echo "-- assistant content after last REAL user is preserved when trailing synthetics exist --"
# Without filtering, the assistant_content slice starts after the LAST user (a synthetic),
# which means the real assistant work between the real user message and the synthetic
# wrapper is dropped — tool_call_count goes to 0 and the score drops to nothing.
assert_eq "tool_call_count keeps real assistant tool use" "1" "$(echo "$r" | jq -r '.tool_call_count')"

echo "-- transcript with ONLY synthetic users yields empty user_msg (no crash) --"
tsyn2=$(mktemp).jsonl
cat > "$tsyn2" <<'JSONL'
{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: blah</local-command-caveat>"}}
{"type":"user","message":{"role":"user","content":"<command-name>/model</command-name>"}}
JSONL
r=$(transcript_parse_current_turn "$tsyn2" "[]" "$CWD")
assert_eq "all-synthetic → empty user_msg" "" "$(echo "$r" | jq -r '.user_msg')"
rm -f "$tsyn" "$tsyn2"

echo ""
echo "Result: $PASS passed, $FAIL failed"
[[ $FAIL -eq 0 ]]
